### ISSUE TITLE
Splash-3x does not provide native inputs

### ISSUE THREAD

**Issue by mariobadr** [SakalisC/Splash-3#3]
Commit d8959049c25c116b010bbbc8c38e4d9fced3e984 incorporates Parsec 3's Splash-2X enhancements to allow for larger input set sizes. However, the input folders themselves have not been updated to include the larger input sets. For example, the barnes application input_native on PARSEC looks like this:

> 4194304
> 123
> 
> 0.025
> 0.05
> 1.0
> 2.0
> 5.0
> 0.075
> 0.25
> NUMPROCS

However, the largest input provided by Splash-3x is `16384` (as opposed to `4194304` above). It would be nice if the native inputs released with Parsec 3.0 were also released here.

**Comment by SakalisC** [comment]
I am currently somewhere with a terrible Internet connection, so I can't download the large PARSEC inputs. I will fix this next week when I will be back home. Thanks for reporting it.

**Comment by SakalisC** [comment]
Fixed in df18c1d. Note that the number of threads is specified in the input files, so you might want to change that number to something more meaningful that just 1.

In PARSEC this is handled by having the runtime system replace the text "NUMPROCS" with the configured number of threads, but for Splash-3 I would have to create different variants for different thread counts, which would require too many files.
